---
abstract: 'Much has changed in twenty years... but THEMA-MEDIA still provides solutions based on proven technologies'
author:
  - 'Theo van Hoesel <Th.J.v.Hoesel@THEMA-MEDIA.nl>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: THEMA-MEDIA
resources:
  bugtracker: https://github.com/THEMA-MEDIA/CPAN-foolishness/issues
  homepage: https://github.com/THEMA-MEDIA/CPAN-foolishness
  repository: https://github.com/THEMA-MEDIA/CPAN-foolishness.git
version: 2014.10.01
