---
abstract: 'Providing solutions with Modern Perl'
author:
  - 'Theo van Hoesel <Th.J.v.Hoesel@THEMA-MEDIA.nl>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: THEMA-MEDIA
version: 2014.10.02
